flags:
  pandoc:
    trypandoc: false
    embed_data_files: true
packages:
- '.'
extra-deps:
- pandoc-types-1.22
#- texmath-0.12
#- haddock-library-1.8.0
#- skylighting-0.8.3.2
#- skylighting-core-0.8.3.2
#- regex-pcre-builtin-0.95.0.8.8.35
#- doclayout-0.2.0.1@sha256:0410e40c4fa8e299b4f5fa03d378111b9d0effdf59134c95882a160637887ba8,2063
#- emojis-0.1
#- jira-wiki-markup-1.0.0
#- HsYAML-0.2.0.0
#- HsYAML-aeson-0.2.0.0
#- doctemplates-0.8.1
#- pandoc-citeproc-0.16.4.1
#- roman-numerals-0.5.1.5@sha256:819d04d9d442b24629dd058f6f0b02bd78e9f9ae99538bc44ca448f1cb2b7b01,1208
ghc-options:
   "$locals": -fhide-source-paths -Wno-missing-home-modules
#
resolver: lts-17.9
allow-newer: true
